openapi: 3.0.0
info:
  version: 1.0.0
  title: Service Request API
  description: API for managing user authentication and service requests

paths:
  /login:
    tags:
    - name
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
      responses:
        200:
          description: OTP sent to email
        default:
          description: Report error (To be implemented)

  /verify:
    post:
      summary: Verify OTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
                  example: 123456
      responses:
        200:
          description: Successfully authenticated. The JWT token is returned in a cookie named `JWT`. You need to include this cookie in subsequent requests.
          headers:
            Set-Cookie:
              schema:
                type: string
                example: JWT=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.abcde12345; Path=/; HttpOnly
        400:
          description: Invalid OTP, error message shown

  /dashboard/servicerequests:
    get:
      summary: Fetch all service requests for a specific user
      parameters:
        - in: cookie
          name: JWT
          schema:
            type: string
            required: true
            description: JWT token containing the userid
            example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiIxMjM0NSJ9.abcde12345
      responses:
        200:
          description: A JSON array of service requests for the specified `userid` from the JWT
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    srn:
                      type: string
                      example: SRN123
                    service:
                      type: string
                      example: "Car Rental"
                    request_raised_on:
                      type: string
                      format: date
                      example: "2024-09-27"
                    request_fulfilled_on:
                      type: string
                      format: date
                      example: "2024-10-01"
                    status:
                      type: string
                      example: "Fulfilled"
        default:
          description: Error message

  /dashboard/servicerequests/{srn}:
    get:
      summary: Fetch detailed service request information
      parameters:
        - in: path
          name: srn
          schema:
            type: string
          required: true
          description: Service request number
        - in: cookie
          name: userid
          schema:
            type: string
          required: true
          description: User ID from cookie
      responses:
        200:
          description: Service request details
          content:
            application/json:
              schema:
                type: object
                properties:
                  srn:
                    type: string
                    example: SRN123
                  type_of_service_request:
                    type: string
                    example: "Car Rental"
                  request_raised_on:
                    type: string
                    format: date
                    example: "2024-09-27"
                  request_fulfilled_on:
                    type: string
                    format: date
                    example: "2024-10-01"
                  status:
                    type: string
                    example: "Fulfilled"
                  per_diem:
                    type: number
                    example: 50.00
                  passenger_details:
                    type: object
                    properties:
                      first_name:
                        type: string
                        example: John
                      last_name:
                        type: string
                        example: Doe
                      emp_id:
                        type: string
                        example: E12345
                      dept:
                        type: string
                        example: IT
                      mob_number:
                        type: string
                        example: 1234567890
                      email:
                        type: string
                        example: john.doe@example.com
                      reason:
                        type: string
                        example: "Business Trip"
                      hod_approval_doc:
                        type: string
                        example: "https://example.com/doc.pdf"
                  service_request:
                    type: object
                    properties:
                      origin:
                        type: string
                        example: "City A"
                      departure:
                        type: string
                        example: "City B"
                      date:
                        type: string
                        format: date
                        example: "2024-09-28"
                      time_prefs:
                        type: string
                        example: "Morning"
                      mob_num:
                        type: string
                        example: 1234567890
                      trip_type:
                        type: string
                        enum: [one, two, multi]
                        example: one
                  request_status:
                    type: string
                    example: "In Progress"
        default:
          description: Error message
          
  /api/request/flight:
    post:
      summary: Request a flight booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                route:
                  type: array
                  items:
                    type: object
                    properties:
                      origin:
                        type: string
                        example: "New York"
                      destination:
                        type: string
                        example: "London"
                immediate_booking:
                  type: boolean
                  example: true
                depart_datetime:
                  type: string
                  format: date-time
                  example: "2024-10-01T10:00:00Z"
                arrive_datetime:
                  type: string
                  format: date-time
                  example: "2024-10-01T14:00:00Z"
                passenger_details:
                  type: object
                  properties:
                    detail:
                      type: object
                      properties:
                        fname:
                          type: string
                          example: "John"
                        lname:
                          type: string
                          example: "Doe"
                        phone:
                          type: string
                          example: "1234567890"
                        email:
                          type: string
                          example: "john.doe@example.com"
                        reason:
                          type: string
                          example: "Business"
                        hod_cer_link:
                          type: string
                          example: "https://example.com/hod_certificate.pdf"
                    self:
                      type: boolean
                      example: false
      responses:
        200:
          description: Flight booking requested successfully
        default:
          description: Error occurred during booking

  /api/request/cab:
    post:
      summary: Request a cab booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                city:
                  type: string
                  example: "San Francisco"
                state:
                  type: string
                  example: "California"
                pickup_address:
                  type: string
                  example: "123 Market St, San Francisco, CA"
                drop_address:
                  type: string
                  example: "456 Mission St, San Francisco, CA"
                time_preference:
                  type: string
                  format: date-time
                  example: "2024-10-01T08:00:00Z"
                passenger_details:
                  type: object
                  properties:
                    detail:
                      type: object
                      properties:
                        fname:
                          type: string
                          example: "John"
                        lname:
                          type: string
                          example: "Doe"
                        phone:
                          type: string
                          example: "1234567890"
                        email:
                          type: string
                          example: "john.doe@example.com"
                        reason:
                          type: string
                          example: "Business"
                        hod_cer_link:
                          type: string
                          example: "https://example.com/hod_certificate.pdf"
                    self:
                      type: boolean
                      example: false
      responses:
        200:
          description: Cab booking requested successfully
        default:
          description: Error occurred during booking

  /api/request/hotel:
    post:
      summary: Request a hotel booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                city:
                  type: string
                  example: "Los Angeles"
                state:
                  type: string
                  example: "California"
                departure_date:
                  type: string
                  format: date
                  example: "2024-10-01"
                checkout_date:
                  type: string
                  format: date
                  example: "2024-10-05"
                departure_time:
                  type: string
                  format: time
                  example: "10:00:00"
                arrival_time:
                  type: string
                  format: time
                  example: "18:00:00"
                time_preference:
                  type: string
                  format: date-time
                  example: "2024-10-01T10:00:00Z"
                passenger_details:
                  type: object
                  properties:
                    detail:
                      type: object
                      properties:
                        fname:
                          type: string
                          example: "John"
                        lname:
                          type: string
                          example: "Doe"
                        phone:
                          type: string
                          example: "1234567890"
                        email:
                          type: string
                          example: "john.doe@example.com"
                        reason:
                          type: string
                          example: "Conference"
                        hod_cer_link:
                          type: string
                          example: "https://example.com/hod_certificate.pdf"
                    self:
                      type: boolean
                      example: false
      responses:
        200:
          description: Hotel booking requested successfully
        default:
          description: Error occurred during booking
